// ALL PRODUCTS FROM PDF - Comprehensive Database

const productsDatabase = [
    // Diwali Trays
    {
        id: 1,
        name: "Zamia Curlyleaf & Snake Plant Tray",
        category: "trays hampers",
        price: 4000,
        size: "medium",
        image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600",
        description: "Beautiful 12\" tray with Zamia Curlyleaf and Snake Plant, featuring Gold Buddha with Blue Metal Hamsa.",
        specs: "Tray 12\", Planter (1) Height 4.5\" x Width 5\", Planter (2) Height 3\" x Width 3\"",
        rating: 4.8,
        reviews: 24,
        badge: "BESTSELLER"
    },
    {
        id: 2,
        name: "Wooden Tray Special",
        category: "trays hampers",
        price: 4000,
        size: "medium",
        image: "https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=600",
        description: "12\" Wooden Tray with Zamia Curlyleaf & Snake Plant, 5\" Buddha Gold, Urli Candle, Wooden Log, Pine Cone.",
        specs: "12\" Wooden Tray, Height 4.5\" x Width 5\", Height 3\" x 4\"",
        rating: 4.9,
        reviews: 31,
        badge: "NEW"
    },
    {
        id: 3,
        name: "Ficus Bonsai Special",
        category: "bonsai trays",
        price: 3800,
        size: "large",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Stunning Ficus Bonsai with Ganesha, Lotus Diya & Moli & Rudraksh.",
        specs: "Height 6.5 inches, Width 16 inches",
        rating: 5.0,
        reviews: 45,
        badge: "BESTSELLER"
    },
    {
        id: 4,
        name: "ZZ Curlyleaf & Aglaonema Tray",
        category: "trays hampers",
        price: 4500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        description: "12\" Wooden Tray with ZZ Curlyleaf & Aglaonema Plant, Hand Painted Wooden Log, Dry Powder Decor, Scented Candle.",
        specs: "12\" Wooden Tray",
        rating: 4.7,
        reviews: 19,
        badge: "NEW"
    },

    // Diwali Hampers
    {
        id: 5,
        name: "Guruji Swaroop Hamper",
        category: "hampers corporate",
        price: 3500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1511406361295-0a1ff814c0ce?w=600",
        description: "German silver frame with Guruji Swaroop, Scented candle, indoor plant, Leatherite rattan tray 10x12 inches.",
        specs: "10x12 inches rattan tray",
        rating: 4.9,
        reviews: 38,
        badge: ""
    },
    {
        id: 6,
        name: "Radha Krishna Hamper",
        category: "hampers",
        price: 3500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1459156212016-c812468e2115?w=600",
        description: "German silver frame with Radha Krishna photo, Indoor plant, scented candle, rattan tray.",
        specs: "Rattan tray",
        rating: 4.8,
        reviews: 27,
        badge: ""
    },
    {
        id: 7,
        name: "Lotus Print Wooden Tray",
        category: "hampers",
        price: 2800,
        size: "small",
        image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600",
        description: "8 inches lotus print wooden tray, Aglaonema indoor plant, Scented candle.",
        specs: "8 inches wooden tray",
        rating: 4.6,
        reviews: 22,
        badge: ""
    },
    {
        id: 8,
        name: "Copper Wellness Hamper",
        category: "hampers corporate",
        price: 3200,
        size: "medium",
        image: "https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=600",
        description: "Pinewood tray 8x8 inches, Copper air tight bottle, Copper glasses, Scented soy candle, Aglaonema indoor plant.",
        specs: "8x8 inches pinewood tray",
        rating: 4.9,
        reviews: 42,
        badge: "BESTSELLER"
    },
    {
        id: 9,
        name: "Antique Basket Hamper",
        category: "hampers",
        price: 4500,
        size: "large",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        description: "Antique wooden basket 15.5 inches, Zamia curly leaf indoor plant in 5 inches, Phool incense sticks, 250 gm almonds in tissue pouch, Soy wax scented candle.",
        specs: "15.5 inches basket",
        rating: 5.0,
        reviews: 35,
        badge: "BESTSELLER"
    },
    {
        id: 10,
        name: "Bonsai Shubh Labh Hamper",
        category: "hampers bonsai",
        price: 3000,
        size: "medium",
        image: "https://images.unsplash.com/photo-1463320726281-696a485928c7?w=600",
        description: "Pinewood tray 10x10 inches, Ficus bonsai with Ganpati, Shubh labh hanging, 2 Moli tea lights, 300 grams almonds.",
        specs: "10x10 inches pinewood tray",
        rating: 4.8,
        reviews: 29,
        badge: ""
    },

    // Rakhi Collection
    {
        id: 11,
        name: "Macrame Basket Rakhi Set",
        category: "hampers",
        price: 2500,
        size: "small",
        image: "https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=600",
        description: "Macrame basket, 2 evil eye mugs, donut vase & bell, Roli teeka plate, Indoor plant, Rakhi & lumba bracelet.",
        specs: "Macrame basket set",
        rating: 4.7,
        reviews: 18,
        badge: ""
    },
    {
        id: 12,
        name: "Acrylic Hamper Rakhi",
        category: "hampers",
        price: 2300,
        size: "small",
        image: "https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=600",
        description: "Acrylic hamper, Indoor plant, Resin photo frame, Rakhi.",
        specs: "Acrylic hamper",
        rating: 4.5,
        reviews: 15,
        badge: ""
    },
    {
        id: 13,
        name: "Mug Planter Set",
        category: "indoor",
        price: 1200,
        size: "small",
        image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
        description: "Mug planter with Palm & snake plant, Miniature brother sister.",
        specs: "Mug planter",
        rating: 4.4,
        reviews: 12,
        badge: ""
    },

    // Indoor Plants
    {
        id: 14,
        name: "Aglaonema Pink Lipstick",
        category: "indoor",
        price: 1400,
        size: "small",
        image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600",
        description: "Beautiful Aglaonema Pink Lipstick with Miniature Fairy with Wings.",
        specs: "Height 4.75\" x Width 5\"",
        rating: 4.9,
        reviews: 142,
        badge: "BESTSELLER"
    },
    {
        id: 15,
        name: "Snow White Plant",
        category: "indoor",
        price: 1200,
        size: "small",
        image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600",
        description: "Elegant Snow White plant in decorative planter.",
        specs: "Height 4\" x Width 5\"",
        rating: 4.6,
        reviews: 87,
        badge: ""
    },
    {
        id: 16,
        name: "Chamaedorea Palm",
        category: "indoor",
        price: 1500,
        size: "small",
        image: "https://images.unsplash.com/photo-1463320726281-696a485928c7?w=600",
        description: "Chamaedorea Palm with Baby Buddha decoration.",
        specs: "Height 4\" x Width 5.5\"",
        rating: 4.8,
        reviews: 95,
        badge: ""
    },
    {
        id: 17,
        name: "Zamia Curlyleaf",
        category: "indoor",
        price: 1500,
        size: "small",
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        description: "Compact Zamia Curlyleaf plant, perfect for desks.",
        specs: "Height 4\" x Width 3\"",
        rating: 4.7,
        reviews: 76,
        badge: ""
    },
    {
        id: 18,
        name: "Big Snake Plant",
        category: "indoor",
        price: 999,
        size: "medium",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        description: "Large air-purifying Snake Plant, great for beginners.",
        specs: "Big Size",
        rating: 4.9,
        reviews: 234,
        badge: "BESTSELLER"
    },
    {
        id: 19,
        name: "Pothos Plant",
        category: "indoor",
        price: 1100,
        size: "medium",
        image: "https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=600",
        description: "Classic Pothos plant, easy to care for.",
        specs: "Height 7.5\"",
        rating: 4.8,
        reviews: 189,
        badge: ""
    },
    {
        id: 20,
        name: "Jade Topiary",
        category: "indoor bonsai",
        price: 1700,
        size: "medium",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Beautiful Jade Topiary with Baby Buddha and Bell.",
        specs: "Height 4.25\" x Width 9\"",
        rating: 4.9,
        reviews: 67,
        badge: ""
    },
    {
        id: 21,
        name: "Peace Lily",
        category: "indoor",
        price: 1400,
        size: "medium",
        image: "https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=600",
        description: "Elegant Peace Lily with white blooms.",
        specs: "Height 5\" x Width 7\"",
        rating: 4.8,
        reviews: 145,
        badge: ""
    },
    {
        id: 22,
        name: "Zamia Curlyleaf Medium",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600",
        description: "Medium-sized Zamia Curlyleaf in elegant planter.",
        specs: "Height 4.2\" x Width 9\"",
        rating: 4.7,
        reviews: 92,
        badge: ""
    },
    {
        id: 23,
        name: "Aglaonema Valentine",
        category: "indoor",
        price: 1200,
        size: "small",
        image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
        description: "Aglaonema Valentine with 2 Pink Swans decoration.",
        specs: "Height 4\" x Width 4.5\"",
        rating: 4.6,
        reviews: 58,
        badge: ""
    },
    {
        id: 24,
        name: "Snake Plant Bed",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        description: "Snake Plant arrangement with Marble finish Buddha.",
        specs: "Height 4.25\", Width 9\"",
        rating: 4.8,
        reviews: 112,
        badge: ""
    },
    {
        id: 25,
        name: "Money Plant with Buddha",
        category: "indoor",
        price: 1700,
        size: "medium",
        image: "https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=600",
        description: "Classic Money Plant with White Buddha.",
        specs: "Height 4\" x Width 9\"",
        rating: 4.9,
        reviews: 198,
        badge: "BESTSELLER"
    },
    {
        id: 26,
        name: "Dual Money Plant",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        description: "2 Varieties of Money Plant with Golden Evil Eye Hanging.",
        specs: "Height 4.2\" x Width 9\" & 5\"",
        rating: 4.8,
        reviews: 87,
        badge: ""
    },
    {
        id: 27,
        name: "Snake Plant with Ganesha",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1463320726281-696a485928c7?w=600",
        description: "Snake Plant (Sansevieria) with Ganesha decoration.",
        specs: "Height 4\" x Width 9\"",
        rating: 4.9,
        reviews: 134,
        badge: ""
    },
    {
        id: 28,
        name: "Ficus Bonsai with Guruji",
        category: "bonsai indoor",
        price: 2500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Ficus Bonsai with Guruji Swaroop, Om and Swastik with fairy lights.",
        specs: "Height 5\", Width 9\"",
        rating: 5.0,
        reviews: 45,
        badge: ""
    },
    {
        id: 29,
        name: "Jade Topiary with Krishna",
        category: "indoor bonsai",
        price: 2500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=600",
        description: "Jade Topiary with brass Krishna with peacock and candle.",
        specs: "Height 3\" x Width 8\"",
        rating: 4.9,
        reviews: 52,
        badge: ""
    },
    {
        id: 30,
        name: "Aglaonema & Lipstick Combo",
        category: "indoor",
        price: 2000,
        size: "medium",
        image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600",
        description: "Aglaonema & Lipstick plant with Couple with Balloon Miniature.",
        specs: "Height 4.2\" x Width 9\" & 5\"",
        rating: 4.7,
        reviews: 63,
        badge: ""
    },
    {
        id: 31,
        name: "Curly ZZ with Buddha",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600",
        description: "Curly ZZ plant with Baby Buddha and Lotus Diya.",
        specs: "Medium size",
        rating: 4.8,
        reviews: 98,
        badge: ""
    },
    {
        id: 32,
        name: "Aglaonema Valentine with Swans",
        category: "indoor",
        price: 2000,
        size: "medium",
        image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
        description: "Aglaonema Valentine with Pink Swans decoration.",
        specs: "Height 4\" x Width 7\"",
        rating: 4.7,
        reviews: 71,
        badge: ""
    },
    {
        id: 33,
        name: "Tall Snake Plants",
        category: "indoor",
        price: 1800,
        size: "medium",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        description: "Tall Snake Plants with Hand Painted Blessed Wooden Log.",
        specs: "Height 4\" x Width 9\"",
        rating: 4.9,
        reviews: 156,
        badge: ""
    },
    {
        id: 34,
        name: "Tall ZZ Plant",
        category: "indoor corporate",
        price: 3800,
        size: "large",
        image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600",
        description: "Premium Tall ZZ Plant with Gold Buddha and Blue Metal Hamsa.",
        specs: "Height 5\" x Width 11\"",
        rating: 5.0,
        reviews: 164,
        badge: "BESTSELLER"
    },
    {
        id: 35,
        name: "Topiary Arrangement",
        category: "indoor corporate",
        price: 3000,
        size: "large",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Elegant Topiary with Brass Murti Chowki, Swastik Candle Roll.",
        specs: "Height 5\" x Width 11\"",
        rating: 4.8,
        reviews: 89,
        badge: ""
    },
    {
        id: 36,
        name: "ZZ Curlyleaf Special",
        category: "indoor",
        price: 2600,
        size: "medium",
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        description: "ZZ Curlyleaf with Hand Painted Wooden Log.",
        specs: "Height 4.2\" x Width 9\" & 5\"",
        rating: 4.7,
        reviews: 74,
        badge: ""
    },
    {
        id: 37,
        name: "Zamia Curlyleaf Premium",
        category: "indoor corporate",
        price: 3200,
        size: "large",
        image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600",
        description: "Premium Zamia Curlyleaf with White 5\" Buddha, Metal Hamsa.",
        specs: "Height 4.2\" x Width 9\"",
        rating: 4.9,
        reviews: 102,
        badge: ""
    },
    {
        id: 38,
        name: "Zamia with Brass Murti",
        category: "indoor",
        price: 3100,
        size: "large",
        image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
        description: "Zamia Curlyleaf with Brass Murti, Chowki, Swastik Matki Candle.",
        specs: "Height 4\" x Width 9\"",
        rating: 4.8,
        reviews: 56,
        badge: ""
    },
    {
        id: 39,
        name: "Hibiscus Plant",
        category: "indoor",
        price: 2800,
        size: "large",
        image: "https://images.unsplash.com/photo-1463320726281-696a485928c7?w=600",
        description: "Beautiful Hibiscus with Metal Customized Sticker of Shiva Shlok.",
        specs: "Height 9\" x Width 11\"",
        rating: 4.7,
        reviews: 48,
        badge: ""
    },
    {
        id: 40,
        name: "Double ZZ Curlyleaf",
        category: "indoor corporate",
        price: 3200,
        size: "large",
        image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600",
        description: "Double ZZ Curlyleaf with Gold 8\" Buddha.",
        specs: "Height 5\" x Width 10\"",
        rating: 4.9,
        reviews: 123,
        badge: ""
    },
    {
        id: 41,
        name: "Jade Topiary Garden",
        category: "indoor bonsai",
        price: 2500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Jade Topiary with Swing and Miniature Garden.",
        specs: "Height 4.25\" x Width 9\"",
        rating: 4.8,
        reviews: 67,
        badge: ""
    },
    {
        id: 42,
        name: "Ficus Bonsai Classic",
        category: "bonsai corporate",
        price: 2500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=600",
        description: "Classic Ficus Bonsai with Gold Buddha & Bells.",
        specs: "Height 5\" x Width 11\"",
        rating: 4.9,
        reviews: 91,
        badge: ""
    },
    {
        id: 43,
        name: "Aglaonema & Snake Plant Combo",
        category: "indoor corporate",
        price: 3200,
        size: "large",
        image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600",
        description: "Premium combo of Aglaonema & Snake Plant with White Buddha & Wooden Hamsa Hand.",
        specs: "Height 5\" x Width 11\"",
        rating: 4.9,
        reviews: 108,
        badge: ""
    },
    {
        id: 44,
        name: "12-Year Ficus Bonsai",
        category: "bonsai corporate",
        price: 4200,
        size: "large",
        image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
        description: "Premium 12-year old Ficus Bonsai with White Buddha and Bell. A masterpiece.",
        specs: "Height 5\" x Width 18\"",
        rating: 5.0,
        reviews: 89,
        badge: "BESTSELLER"
    },
    {
        id: 45,
        name: "Syngonium Brass Frame Set",
        category: "indoor corporate",
        price: 3500,
        size: "medium",
        image: "https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=600",
        description: "Plant syngonium in 10 inches wooden tray, Brass frame with picture, brass lamp and glass jar with edibles.",
        specs: "10 inches wooden tray",
        rating: 4.8,
        reviews: 72,
        badge: ""
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = productsDatabase;
}
